# Generated by Django 3.0 on 2023-10-11 08:56

from django.db import migrations
from django.db import models
from lettings.models import Address, Letting
from profiles.models import Profile

def custom_migration(apps, schema_editor):
    """
        Custom migration.
        this should transfer every "Address" and "Letting" to lettings app and every "Profile" to profiles app.
        no need to remove them from oc_lettings_site app. ( they'll be flushed by basic migration )
    """
    OldAdress : Address = apps.get_model('oc_lettings_site', 'Address')
    OldLetting : Letting = apps.get_model('oc_lettings_site', 'Letting')
    OldProfile : Profile = apps.get_model('oc_lettings_site', 'Profile')

    NewAdress : Address = apps.get_model('lettings', 'Adress')
    NewLetting : Letting = apps.get_model('lettings', 'Letting')
    NewProfile : Profile = apps.get_model('profiles', 'Profile')

    for old_address in OldAdress.objects.all():
        new_address = NewAdress.objects.create(
            number = old_address.number,
            street = old_address.street,
            city = old_address.city,
            state = old_address.state,
            zip_code = old_address.zip_code,
            country_iso_code = old_address.country_iso_code
        )
        new_address.save()

    for old_letting in OldLetting.objects.all():
        new_letting = NewLetting.objects.create(
            title = old_letting.title,
            address = NewAdress.objects.get(pk=old_letting.address.pk)
        )
        new_letting.save()
    
    for old_profile in OldProfile.objects.all():
        new_profile = NewProfile.objects.create(
            user = old_profile.user,
            favorite_city = old_profile.favorite_city
        )
        new_profile.save()

    


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(custom_migration),
        migrations.RemoveField(
            model_name='letting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Letting',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
