# Generated by Django 3.0 on 2023-10-26 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oc_lettings_site", "0001_initial"),
    ]

    operations = [
        # NOTE : this migration is commented out because it was created automatically
        # by Django when moving the Address, Letting and Profile models from
        # oc_lettings_site app to profiles and lettings apps
        # we want to keep the db tables and data
        # migrations.RemoveField(
        #     model_name='letting',
        #     name='address',
        # ),
        # migrations.RemoveField(
        #     model_name='profile',
        #     name='user',
        # ),
        # migrations.DeleteModel(
        #     name='Address',
        # ),
        # migrations.DeleteModel(
        #     name='Letting',
        # ),
        # migrations.DeleteModel(
        #     name='Profile',
        # ),
    ]
